[config]

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-style.css.tmpl"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -SIGUSR2 waybar || true"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf.tmpl"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -SIGUSR1 kitty || true"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml.tmpl"
output_path = "~/.cache/matugen/starship.toml"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc.tmpl"
output_path = "~/.config/fastfetch/matugen.jsonc"

[templates.wofi]
input_path = "~/.config/matugen/templates/wofi-style.css.tmpl"
output_path = "~/.config/wofi/matugen.css"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf.tmpl"
output_path = "~/.config/hypr/hyprlock-matugen.conf"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hypr-colors.lua.tmpl"
output_path = "~/.config/hypr/matugen-colors.lua"
post_hook = "hyprctl reload || true"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-style.css.tmpl"
output_path = "~/.config/swaync/matugen.css"
post_hook = "swaync-client --reload-css --skip-wait || true"
