local programs = require("programs")

hl.on("hyprland.start", function()
    hl.exec_cmd(programs.terminal)
    hl.exec_cmd("bash ~/.config/waybar/launch.sh")
    hl.exec_cmd("bash ~/.config/hypr/launch-swaync.sh")
    hl.exec_cmd("awww-daemon")
    --- OLD backend hl.exec_cmd("hyprpaper")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd(programs.browser)
end)
