# preload = /home/dana/valley_mountains_2560x1440.png
# preload = /home/dana/wallpapers/koifish_dragon.png
# preload = /home/dana/deer_mountain_1440x2560.png
# preload = /home/dana/wallpapers/nebula/Wallpapers/Distort/10.png
# preload = /home/dana/wallpapers/nebula/Wallpapers/Grain/3.jpg
wallpaper {
    monitor = DP-1
    path = /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/40.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/10.jpg
    fit_mode = cover
}

splash = false

#preload = /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/40.jpg
#preload = /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/10.jpg
#preload = /home/dana/wallpapers/mount_fuji_2560x1440.png
#wallpaper = DP-2, /home/dana/valley_mountains_2560x1440.png
#wallpaper = DP-2, /home/dana/wallpapers/koifish_dragon.png
#wallpaper = DP-2, /home/dana/wallpapers/nebula/Wallpapers/Distort/10.png
# wallpaper = DP-2, /home/dana/wallpapers/nebula/Wallpapers/Grain/3.jpg
#wallpaper = DP-1, /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/40.jpg
# wallpaper = DP-3, /home/dana/deer_mountain_1440x2560.png
#wallpaper = DP-2, /home/dana/wallpapers/mount_fuji_2560x1440.png
#wallpaper = DP-2, /home/dana/wallpapers/nebula/Wallpapers/Fractal Maze/10.jpg

