font_family 		Iosevka Nerd Font
bond_font		Iosevka Nerd Font
italic_font		Iosevka Nerd Font
bold_italic_font	auto
font_size 		13

# BINDINGS
map shift+left select_word_left
map shift+right select_word_right
map shift+up select_to_previous_line
map shift+down select_to_next_line

# CURSOR
cursor_shape beam
cursor_beam_thickness 2
cursor_blink_interval 1 ease-in-out
cursor_trail 2

# COLOURS
background_opacity 0.65

# Scrollback
scrollback_lines 5000

url_color #33A1FD
url_style straight

padding = 0
underline_hyperlinks always

background #10151c
background_opacity 0.82
